const plants = [
  {
    name        : 'Монстера Обликва',
    nameEng     : 'monstera_obliqua',
    lastDate    : '2021-12-19',
    interval    : 3,
    dayWeek     : '',
    nextDayWeek : '',
    daysAgo     : '',
    nextDate    : '',
    transplanted: '2021-11-22',
  },
  {
    name        : 'Герань',
    nameEng     : 'geranium',
    lastDate    : '2021-12-23',
    interval    : 9,
    dayWeek     : '',
    nextDayWeek : '',
    daysAgo     : '',
    nextDate    : '',
    transplanted: '2021-11-27',
  },
  {
    name        : 'Хлорофитум ',
    nameEng     : 'hlorophytum',
    lastDate    : '2021-12-19',
    interval    : 7,
    dayWeek     : '',
    nextDayWeek : '',
    daysAgo     : '',
    nextDate    : '',
    transplanted: '',
  },
  {
    name        : 'Сингониум ',
    nameEng     : 'syngonium',
    lastDate    : '2021-12-19',
    interval    : 7,
    dayWeek     : '',
    nextDayWeek : '',
    daysAgo     : '',
    nextDate    : '',
    transplanted: '',
  },
  {
    name        : 'Фиалка Big',
    nameEng     : 'violetBig',
    lastDate    : '2021-16-16',
    interval    : 5,
    dayWeek     : '',
    nextDayWeek : '',
    daysAgo     : '',
    nextDate    : '',
    transplanted: '2021-12-06',
  },
  {
    name        : 'Фиалка Small',
    nameEng     : 'violetSmall',
    lastDate    : '2021-12-16',
    interval    : 5,
    dayWeek     : '',
    nextDayWeek : '',
    daysAgo     : '',
    nextDate    : '',
    transplanted: '2021-12-06',
  },
]

export {
  plants
}