const plants = [
  {
    available   : true,
    name        : 'Монстера Обликва',
    nameEng     : 'monsteraObliqua',
    lastDate    : '2023-05-07',
    interval    : 2,
    dayWeek     : '',
    nextDayWeek : '',
    daysAgo     : '',
    nextDate    : '',
    transplanted: '2021-11-24',
  },
  {
    available   : true,
    name        : 'Хлорофитум ',
    nameEng     : 'hlorophytum',
    lastDate    : '2023-05-07',
    interval    : 2,
    dayWeek     : '',
    nextDayWeek : '',
    daysAgo     : '',
    nextDate    : '',
    transplanted: '2022-02-19',
  },
  {
    available   : true,
    name        : 'Фикус',
    nameEng     : 'ficus',
    lastDate    : '2023-05-07',
    interval    : 2,
    dayWeek     : '',
    nextDayWeek : '',
    daysAgo     : '',
    nextDate    : '',
    transplanted: '2023-04-12',
  },
  {
    available   : true,
    name        : 'Хамедорея Элеганс',
    nameEng     : 'hamedoreaElegance',
    lastDate    : '2023-05-07',
    interval    : 2,
    dayWeek     : '',
    nextDayWeek : '',
    daysAgo     : '',
    nextDate    : '',
    transplanted: '',
  },
  
  // ↓ empty ↓
  {
    available   : false,
    name        : 'Сингониум ',
    nameEng     : 'syngonium',
    lastDate    : '2022-02-19',
    interval    : 7,
    dayWeek     : '',
    nextDayWeek : '',
    daysAgo     : '',
    nextDate    : '',
    transplanted: '',
  },
  {
    available   : false,
    name        : 'Герань',
    nameEng     : 'geranium',
    lastDate    : '2022-02-19',
    interval    : 9,
    dayWeek     : '',
    nextDayWeek : '',
    daysAgo     : '',
    nextDate    : '',
    transplanted: '2022-02-18',
  },
]

export {
  plants
}
